"""empty message

Revision ID: 041e83e9a16e
Revises: 825d5878cecb
Create Date: 2020-08-11 14:30:29.756126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041e83e9a16e'
down_revision = '825d5878cecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('distance', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'distance')
    # ### end Alembic commands ###
