"""empty message

Revision ID: 2ecda4f9a8f7
Revises: 041e83e9a16e
Create Date: 2020-08-13 14:27:46.599007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecda4f9a8f7'
down_revision = '041e83e9a16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'quantity')
    # ### end Alembic commands ###
