"""Add accept policy field

Revision ID: 3ddb763db202
Revises: 2ecda4f9a8f7
Create Date: 2020-09-04 17:08:21.719932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddb763db202'
down_revision = '2ecda4f9a8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accept_policy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accept_policy')
    # ### end Alembic commands ###
